import { useEffect, useCallback, useRef, useState, type ReactNode } from "react";
import { Router, useRouter } from "@/router";
import { CommandPalette } from "@/components/command-palette";
import { ViewTabStrip } from "@/components/view-tab-strip";
import { ShortcutsDialog } from "@/components/shortcuts-dialog";
import { ConnectClaudeDialog, OPEN_CONNECT_CLAUDE_EVENT } from "@/components/connect-claude-dialog";
import { DocsRouter } from "@/docs/docs-router";
import { LearnRouter } from "@/learn/learn-router";
import { ErrorBoundary } from "@/components/error-boundary";
import { ToastContainer, toast } from "@/components/ui/toast";
import {
  DockviewReact,
  themeLight,
  type DockviewReadyEvent,
  type DockviewApi,
  type IDockviewPanelProps,
} from "dockview-react";
import "dockview-react/dist/styles/dockview.css";
import "./app.css";
import { ProjectPanel } from "./panels/project-panel";
import Inspector from "./panels/inspector";
import { GraphPanel } from "./graph/graph-panel";
import { ViewportPanel } from "./viewport/viewport-panel";
import { BreadboardPanel } from "./breadboard/breadboard-panel";
import { SerialMonitor } from "./panels/serial-monitor";
import { PinInspector } from "./panels/pin-inspector";
import { DebuggerPanel } from "./panels/debugger-panel";
import { DiagramPanel } from "./panels/diagram-panel";
import { OledDisplayPanel } from "./panels/oled-display-panel";

import { BottomToolbar } from "./toolbar/bottom-toolbar";
import { useScene } from "./store/scene-context";
import { useGraph } from "./store/graph-context";
import { useBoard } from "./store/board-context";
import { AppProviders } from "./app-providers";
import { DockviewContext } from "./store/dockview-context";
import { useViewMenuCommands } from "./store/use-view-menu-commands";
import { useViewMenuSync } from "./store/use-view-menu-sync";
import { ProjectLoader } from "./project/project-loader";
import { useGraphPersistence } from "./project/use-graph-persistence";
import { useBoardPersistence } from "./project/use-board-persistence";
import { useLiveBoardSync } from "./project/use-live-board-sync";
import { restorePairedPort } from "./simulator/web-serial-port-store";
import { loadAllCustomParts } from "@/components/catalog/custom-parts-loader";
import { SketchEditor } from "./editor/sketch-editor";
import { SchematicPanel } from "./schematic/schematic-panel";
import { LibraryManager } from "./editor/library-manager";
import { useProject } from "./project/project-context";
import { syncCodegenToBoard } from "./store/graph-scene-bridge";
import {
  generateSketchFromBoard,
  isAutoGeneratedSketch,
} from "./simulator/board-to-sketch";
import { boardCatalog } from "./learn/board-catalog";
import { decodeDiagramFromUrl, diagramToBoardState } from "@dreamer/schemas";
import { useCurrentUser } from "./auth/use-current-user";
import { ApiKeyDialog, OPEN_API_KEY_EVENT } from "./auth/api-key-dialog";
import { LocalNoSessionScreen } from "./auth/local-no-session-screen";
import { PreviewBanner } from "./auth/preview-banner";
import { MotionEditorPage } from "./motion/motion-editor-page";

// Dockview panel wrappers — each wrapped in an ErrorBoundary
function ProjectFilesPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Project"><ProjectPanel /></ErrorBoundary>;
}

function BreadboardDockPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Breadboard"><BreadboardPanel /></ErrorBoundary>;
}

function InspectorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Inspector"><Inspector /></ErrorBoundary>;
}

function GraphEditorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Graph"><GraphPanel /></ErrorBoundary>;
}

function ViewportPanelWrapper(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Viewport"><ViewportPanel /></ErrorBoundary>;
}

function SerialMonitorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Serial Monitor"><SerialMonitor /></ErrorBoundary>;
}

function PinInspectorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Pin Inspector"><PinInspector /></ErrorBoundary>;
}


function SketchEditorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Sketch Editor"><SketchEditor /></ErrorBoundary>;
}

function SchematicPanelWrapper(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Schematic"><SchematicPanel /></ErrorBoundary>;
}

function LibraryManagerPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Libraries"><LibraryManager /></ErrorBoundary>;
}

function DiagramEditorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Diagram"><DiagramPanel /></ErrorBoundary>;
}

function OledDockPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="OLED Display"><OledDisplayPanel /></ErrorBoundary>;
}

function DebuggerDockPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Debugger"><DebuggerPanel /></ErrorBoundary>;
}

const components = {
  projectFiles: ProjectFilesPanel,
  breadboard: BreadboardDockPanel,
  inspector: InspectorPanel,
  graph: GraphEditorPanel,
  viewport: ViewportPanelWrapper,
  serialMonitor: SerialMonitorPanel,
  pinInspector: PinInspectorPanel,

  sketchEditor: SketchEditorPanel,
  schematic: SchematicPanelWrapper,
  libraryManager: LibraryManagerPanel,
  diagram: DiagramEditorPanel,
  oledDisplay: OledDockPanel,
  debugger: DebuggerDockPanel,
};

function AppInner() {
  const { state, send } = useScene();
  const { state: boardState, send: boardSend } = useBoard();
  const { state: graphState } = useGraph();
  const project = useProject();
  useGraphPersistence();
  const { saveNow } = useBoardPersistence();
  // Live bridge: apply out-of-band board edits (e.g. from the `dreamer mcp`
  // server while chatting with Claude) to the canvas in real time.
  useLiveBoardSync();

  // Re-acquire any previously-granted WebSerial port so hosted users don't
  // have to re-pair their board on every reload. No-op outside Chromium /
  // when no permission has been granted yet.
  useEffect(() => { void restorePairedPort(); }, []);

  // Load user-authored custom components from the sidecar once on boot so they
  // appear in the palette and simulate like built-ins.
  useEffect(() => { void loadAllCustomParts(); }, []);
  const dockviewApiRef = useRef<DockviewApi | null>(null);
  // The same API as the ref, mirrored into state so the view tab strip and the
  // native-menu bridge re-render/re-subscribe once Dockview is ready (a ref
  // mutation alone wouldn't trigger that).
  const [dockviewApi, setDockviewApi] = useState<DockviewApi | null>(null);
  // Route native macOS View-menu commands to the Dockview API. No-op in a
  // plain browser, where the menu event never fires.
  useViewMenuCommands(dockviewApi);
  // Mirror which view panels are open onto the native View-menu checkmarks.
  // No-op outside the desktop shell.
  useViewMenuSync(dockviewApi);
  // Track which projectId we have already hydrated for. switchProject() now
  // re-runs hydration cleanly without leaking state from the previous project.
  const boardHydratedForRef = useRef<string | null>(null);
  const [cmdPaletteOpen, setCmdPaletteOpen] = useState(false);
  const [shortcutsOpen, setShortcutsOpen] = useState(false);
  const [connectClaudeOpen, setConnectClaudeOpen] = useState(false);

  // CLI/desktop: prompt for an Anthropic API key when none is configured.
  // `mode`/`hasApiKey` come from /api/auth/me (resolved by the time AppInner
  // mounts, since AuthGate already gated on `loading`).
  const { mode, hasApiKey } = useCurrentUser();
  const [apiKeyOpen, setApiKeyOpen] = useState(mode === "dev" && !hasApiKey);

  // Open the Connect-Claude dialog when the command palette dispatches its event.
  useEffect(() => {
    const open = () => setConnectClaudeOpen(true);
    window.addEventListener(OPEN_CONNECT_CLAUDE_EVENT, open);
    return () => window.removeEventListener(OPEN_CONNECT_CLAUDE_EVENT, open);
  }, []);

  // Re-open the API-key dialog when a chat request reports a missing key.
  useEffect(() => {
    const open = () => setApiKeyOpen(true);
    window.addEventListener(OPEN_API_KEY_EVENT, open);
    return () => window.removeEventListener(OPEN_API_KEY_EVENT, open);
  }, []);

  // Hydrate board state on first render — and again after switchProject().
  //
  // Two paths:
  // 1. Normal: load from the user's project file (API-backed).
  // 2. /editor?learn=<key>: load a lesson's catalog board instead, so
  //    clicking "Open in IDE →" from /learn lands you in a playable copy
  //    of the circuit. The URL param is stripped after load so a refresh
  //    goes back to the user's saved project. NOTE: autosave has a 3-second
  //    hydration grace window, which gives users a moment to navigate away
  //    before the lesson board overwrites their saved project.
  useEffect(() => {
    if (boardHydratedForRef.current === project.projectId) return;
    boardHydratedForRef.current = project.projectId;

    const url = new URL(window.location.href);
    const learnKey = url.searchParams.get("learn");
    if (learnKey && boardCatalog[learnKey]) {
      boardSend({ type: "LOAD_BOARD", state: boardCatalog[learnKey] });
      // Strip the query param so refresh returns to the normal project flow.
      url.searchParams.delete("learn");
      window.history.replaceState(null, "", url.pathname + url.search + url.hash);
      return;
    }

    // ?diagram=<lz-string-encoded> — someone shared a circuit URL. Decode,
    // validate, load, and strip the param so refresh doesn't re-apply the
    // shared diagram over the user's own saved project. ?learn= takes
    // precedence (handled above) because lesson links are curated; ?diagram=
    // comes from peer sharing.
    const diagramParam = url.searchParams.get("diagram");
    if (diagramParam) {
      url.searchParams.delete("diagram");
      window.history.replaceState(null, "", url.pathname + url.search + url.hash);
      const decoded = decodeDiagramFromUrl(diagramParam);
      if (!decoded.ok) {
        toast.error(`Could not load shared diagram: ${decoded.error}`);
        return;
      }
      const parsed = diagramToBoardState(decoded.data);
      if (!parsed.ok) {
        const preview = parsed.errors
          .slice(0, 2)
          .map((e) => (e.path ? `${e.path}: ${e.message}` : e.message))
          .join("; ");
        toast.error(`Shared diagram failed validation: ${preview}`);
        return;
      }
      boardSend({ type: "LOAD_BOARD", state: parsed.boardState });
      const compCount = Object.keys(parsed.boardState.components).length;
      const wireCount = Object.keys(parsed.boardState.wires).length;
      toast.success(
        `Loaded from shared link — ${compCount} component${compCount === 1 ? "" : "s"}, ${wireCount} wire${wireCount === 1 ? "" : "s"}.`,
        {
          duration: 8000,
          action: {
            label: "Undo",
            onClick: () => boardSend({ type: "UNDO" } as never),
          },
        },
      );
      return;
    }

    const pf = project.projectFile;
    if (pf.boardState) {
      boardSend({ type: "LOAD_BOARD", state: pf.boardState });
    }
  }, [project.projectId, project.projectFile, boardSend]);

  // Sync codegen to board whenever graph nodes/edges change.
  // Skip during the initial hydration — graph persistence replays saved nodes,
  // which would trigger codegen and overwrite the loaded sketchCode. The skip
  // guard is keyed by projectId so a switchProject() also gets a clean replay.
  const prevNodesRef = useRef(graphState.nodes);
  const prevEdgesRef = useRef(graphState.edges);
  const graphHydratedForRef = useRef<string | null>(null);
  useEffect(() => {
    // Reset prev refs and hydration flag whenever the project changes so the
    // next hydration replay isn't mistaken for a user edit.
    if (graphHydratedForRef.current !== project.projectId) {
      graphHydratedForRef.current = null;
      prevNodesRef.current = graphState.nodes;
      prevEdgesRef.current = graphState.edges;
    }

    if (
      graphState.nodes !== prevNodesRef.current ||
      graphState.edges !== prevEdgesRef.current
    ) {
      prevNodesRef.current = graphState.nodes;
      prevEdgesRef.current = graphState.edges;
      // Skip the first change after hydration (graph replay)
      if (graphHydratedForRef.current !== project.projectId) {
        graphHydratedForRef.current = project.projectId;
        return;
      }
      syncCodegenToBoard(graphState.nodes, graphState.edges, boardSend);
    }
  }, [graphState.nodes, graphState.edges, boardSend, project.projectId]);

  // Auto-generate sketch from board components when sketch is empty/auto-generated.
  // Skips regeneration when both components AND sketch changed in the same update
  // (e.g., agent/template placed components and wrote a sketch in one batch).
  const prevComponentsRef = useRef(boardState.components);
  const prevWiresRef = useRef(boardState.wires);
  const prevSketchRef = useRef(boardState.sketchCode);
  useEffect(() => {
    const componentsChanged =
      boardState.components !== prevComponentsRef.current ||
      boardState.wires !== prevWiresRef.current;
    const sketchChanged = boardState.sketchCode !== prevSketchRef.current;

    prevComponentsRef.current = boardState.components;
    prevWiresRef.current = boardState.wires;
    prevSketchRef.current = boardState.sketchCode;

    // If both changed in the same render, the sketch was intentionally set
    // (by agent/template) — don't overwrite it with auto-generated code.
    if (componentsChanged && sketchChanged) return;

    if (componentsChanged && isAutoGeneratedSketch(boardState.sketchCode)) {
      const generated = generateSketchFromBoard(boardState.components, boardState.wires);
      if (generated !== boardState.sketchCode) {
        boardSend({ type: "UPDATE_SKETCH", code: generated });
      }
    }
  }, [boardState.components, boardState.wires, boardState.sketchCode, boardSend]);

  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      // Cmd/Ctrl+S — save project (works from anywhere, including editors)
      if ((e.metaKey || e.ctrlKey) && e.key === "s") {
        e.preventDefault();
        saveNow();
        return;
      }

      // Cmd/Ctrl+K — command palette
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        setCmdPaletteOpen((prev) => !prev);
        return;
      }

      // ? — keyboard shortcuts help (only when not typing)
      if (e.key === "?" && !e.metaKey && !e.ctrlKey) {
        const tag = (e.target as HTMLElement).tagName;
        if (tag !== "INPUT" && tag !== "TEXTAREA" && !(e.target as HTMLElement).closest(".cm-editor")) {
          e.preventDefault();
          setShortcutsOpen((prev) => !prev);
          return;
        }
      }

      const target = e.target as HTMLElement
      const tag = target.tagName
      if (tag === "INPUT" || tag === "TEXTAREA") return;

      // Skip when focus is inside a CodeMirror editor — it has its own undo/redo
      if (target.closest(".cm-editor")) return;

      // Undo / Redo (both scene + board)
      if ((e.metaKey || e.ctrlKey) && e.key === "z") {
        e.preventDefault();
        send({ type: e.shiftKey ? "REDO" : "UNDO" });
        boardSend({ type: e.shiftKey ? "REDO" : "UNDO" });
        return;
      }

      if (e.key === "Delete" || e.key === "Backspace") {
        if (boardState.selectedId) {
          const isWire = boardState.selectedId in (boardState.wires ?? {});
          const name = isWire
            ? "Wire"
            : boardState.components[boardState.selectedId]?.name ?? "Component";
          if (isWire) {
            boardSend({ type: "REMOVE_WIRE", id: boardState.selectedId });
          } else {
            boardSend({ type: "REMOVE_COMPONENT", id: boardState.selectedId });
          }
          boardSend({ type: "SELECT", id: null });
          toast.info(`Deleted ${name} — press Cmd+Z to undo`);
        } else if (state.selectedId) {
          send({ type: "REMOVE", id: state.selectedId });
          toast.info("Deleted — press Cmd+Z to undo");
        }
      }
      if (e.key === "Escape") {
        send({ type: "SELECT", id: null });
        boardSend({ type: "SELECT", id: null });
      }
    }
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [state.selectedId, boardState.selectedId, send, boardSend, saveNow]);

  const LAYOUT_STORAGE_KEY = "dreamer:dockview-layout";

  const onReady = useCallback((event: DockviewReadyEvent) => {
    const api = event.api;
    dockviewApiRef.current = api;
    setDockviewApi(api);

    // Clear stale layouts from before Arduino simulator conversion.
    // The old layout references "canvas" and missing panels — force a fresh default.
    const LAYOUT_VERSION = "arduino-sim-v16";
    const saved = localStorage.getItem(LAYOUT_STORAGE_KEY);
    const savedVersion = localStorage.getItem(LAYOUT_STORAGE_KEY + ":version");
    if (saved && savedVersion === LAYOUT_VERSION) {
      try {
        const layout = JSON.parse(saved) as ReturnType<DockviewApi["toJSON"]>;
        api.fromJSON(layout);
        return setupPersistence(api);
      } catch {
        localStorage.removeItem(LAYOUT_STORAGE_KEY);
      }
    } else {
      // Remove stale layout
      localStorage.removeItem(LAYOUT_STORAGE_KEY);
    }

    // Default layout = the Build workspace mode's tab set, so the initial
    // view matches the Build button that's highlighted on first load:
    //   Components | Canvas | Sketch / Libraries | Schematic (top) / Inspector (bottom)
    // Other panels (Serial, Pin Inspector, Diagram) appear when you switch into
    // Simulate / Debug or open them from the tab strip.
    const totalWidth = api.width;
    const totalHeight = api.height;

    const projectFilesPanel = api.addPanel({
      id: "projectFiles",
      component: "projectFiles",
      title: "Components",
    });

    const canvasPanel = api.addPanel({
      id: "breadboard",
      component: "breadboard",
      title: "Breadboard",
      position: { referencePanel: projectFilesPanel, direction: "right" },
    });

    // Sketch editor in the third column, with Libraries as a sibling tab.
    const sketchPanel = api.addPanel({
      id: "sketchEditor",
      component: "sketchEditor",
      title: "Sketch",
      position: { referencePanel: canvasPanel, direction: "right" },
    });

    api.addPanel({
      id: "libraryManager",
      component: "libraryManager",
      title: "Libraries",
      position: { referencePanel: sketchPanel, direction: "within" },
    });

    sketchPanel.api.setActive();

    // Right column: Schematic on top, Inspector stacked below it.
    const schematicPanel = api.addPanel({
      id: "schematic",
      component: "schematic",
      title: "Schematic",
      position: { referencePanel: sketchPanel, direction: "right" },
    });

    const inspectorPanel = api.addPanel({
      id: "inspector",
      component: "inspector",
      title: "Inspector",
      position: { referencePanel: schematicPanel, direction: "below" },
    });

    projectFilesPanel.api.setSize({ width: totalWidth * 0.14 });
    canvasPanel.api.setSize({ width: totalWidth * 0.36 });
    sketchPanel.api.setSize({ width: totalWidth * 0.25 });
    schematicPanel.api.setSize({ width: totalWidth * 0.25 });
    inspectorPanel.api.setSize({ height: totalHeight * 0.45 });

    setupPersistence(api);
  }, []);

  const debounceRef = useRef<ReturnType<typeof setTimeout>>(undefined);

  function setupPersistence(api: DockviewApi) {
    api.onDidLayoutChange(() => {
      clearTimeout(debounceRef.current);
      debounceRef.current = setTimeout(() => {
        const layout = api.toJSON();
        localStorage.setItem(LAYOUT_STORAGE_KEY, JSON.stringify(layout));
        localStorage.setItem(LAYOUT_STORAGE_KEY + ":version", "arduino-sim-v16");
      }, 300);
    });
  }

  return (
    <DockviewContext.Provider value={dockviewApiRef}>
      {/* Column layout: the view tab strip sits on top; Dockview fills the
          rest. The BottomToolbar is a floating overlay anchored bottom-center
          — it carries its own card chrome (border + bg-card + shadow) rather
          than a full-width strip, so the underlying panels bleed to the edges
          instead of reserving a persistent ~56px dark row that read as visual
          distraction in AI mode. pointer-events-none on the overlay keeps the
          canvas fully draggable through empty space around the pill; the card
          itself re-enables pointer-events for interaction. */}
      <div className="relative flex h-full w-full flex-col">
        <ViewTabStrip api={dockviewApi} />
        <div className="relative min-h-0 flex-1">
          <div className="absolute inset-0 dockview-theme-light">
            <DockviewReact
              onReady={onReady}
              components={components}
              theme={themeLight}
              className="h-full"
            />
          </div>
        </div>
        <div className="pointer-events-none absolute inset-x-0 bottom-0 z-10">
          <BottomToolbar />
        </div>
      </div>
      <CommandPalette open={cmdPaletteOpen} onClose={() => setCmdPaletteOpen(false)} />
      <ShortcutsDialog open={shortcutsOpen} onClose={() => setShortcutsOpen(false)} />
      <ConnectClaudeDialog
        open={connectClaudeOpen}
        onClose={() => setConnectClaudeOpen(false)}
        projectId={project.projectId}
      />
      <ApiKeyDialog open={apiKeyOpen} onClose={() => setApiKeyOpen(false)} />
    </DockviewContext.Provider>
  );
}

function AppOrDocs() {
  const { path, navigate } = useRouter();

  // Redirect root to the editor.
  useEffect(() => {
    if (path === "/") navigate("/editor");
  }, [path, navigate]);

  if (path.startsWith("/documentation")) {
    return <DocsRouter />;
  }
  if (path.startsWith("/learn")) {
    return <LearnRouter />;
  }
  if (path.startsWith("/motion")) {
    return (
      <>
        <MotionEditorPage />
        <PreviewBanner />
      </>
    );
  }
  // /editor (and /, briefly, until the redirect fires) render the main app.
  return (
    <ProjectLoader>
      <AppProviders>
        <AppInner />
      </AppProviders>
      <PreviewBanner />
    </ProjectLoader>
  );
}

// ── Auth gate ────────────────────────────────────────────────────────────
//
// Single source of truth for who sees the app: we read `/api/auth/me` via
// `useCurrentUser` and pick a top-level tree based on mode + user. The
// gate deliberately does NOT use `useEffect` — it derives the decision
// directly from the hook's return, which is stable across renders.
//
// Mode semantics:
//   - "dev":    bun run dev with BREADBOX_DEV_SKIP_AUTH=1. Skip the gate
//               entirely — no login, no redirect.
//   - "hosted": Railway deploy. Anonymous visitors see the full editor
//               as a live-preview, with mutations blocked behind a
//               "Sign in with GitHub" banner. Logged-in users get the
//               normal experience.
//   - "local":  `dreamer headed` CLI. Without a cookie, show the
//               "restart your CLI" screen. OAuth isn't a thing here.
function AuthGate({ children }: { children: ReactNode }) {
  const { user, mode, loading } = useCurrentUser();

  if (loading) return null;
  if (mode === "dev") return <>{children}</>;
  if (user) return <>{children}</>;
  if (mode === "hosted") return <>{children}</>;
  return <LocalNoSessionScreen />;
}

export default function App() {
  return (
    <ErrorBoundary name="App">
      <Router>
        <AuthGate>
          <AppOrDocs />
        </AuthGate>
      </Router>
      <ToastContainer />
    </ErrorBoundary>
  );
}
