import { useEffect, useCallback, useRef, useState } from "react";
import { Router, useRouter } from "@/router";
import { CommandPalette } from "@/components/command-palette";
import { DocsRouter } from "@/docs/docs-router";
import { ErrorBoundary } from "@/components/error-boundary";
import { ToastContainer, toast } from "@/components/ui/toast";
import {
  DockviewReact,
  type DockviewReadyEvent,
  type DockviewApi,
  type IDockviewPanelProps,
} from "dockview-react";
import "dockview-react/dist/styles/dockview.css";
import "./app.css";
import { ProjectPanel } from "./panels/project-panel";
import Inspector from "./panels/inspector";
import { GraphPanel } from "./graph/graph-panel";
import { ViewportPanel } from "./viewport/viewport-panel";
import { BreadboardPanel } from "./breadboard/breadboard-panel";
import { SerialMonitor } from "./panels/serial-monitor";
import { PinInspector } from "./panels/pin-inspector";
import { BottomToolbar } from "./toolbar/bottom-toolbar";
import { SceneContext, useScene } from "./store/scene-context";
import { GraphContext, useGraph } from "./store/graph-context";
import { BoardContext, useBoard } from "./store/board-context";
import { DockviewContext } from "./store/dockview-context";
import { ProjectLoader } from "./project/project-loader";
import { useGraphPersistence } from "./project/use-graph-persistence";
import { useBoardPersistence } from "./project/use-board-persistence";
import { SketchEditor } from "./editor/sketch-editor";
import { SchematicPanel } from "./schematic/schematic-panel";
import { LibraryManager } from "./editor/library-manager";
import { useProject } from "./project/project-context";
import { syncCodegenToBoard } from "./store/graph-scene-bridge";
import {
  generateSketchFromBoard,
  isAutoGeneratedSketch,
} from "./simulator/board-to-sketch";

// Dockview panel wrappers — each wrapped in an ErrorBoundary
function ProjectFilesPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Project"><ProjectPanel /></ErrorBoundary>;
}

function BreadboardDockPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Breadboard"><BreadboardPanel /></ErrorBoundary>;
}

function InspectorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Inspector"><Inspector /></ErrorBoundary>;
}

function GraphEditorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Graph"><GraphPanel /></ErrorBoundary>;
}

function ViewportPanelWrapper(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Viewport"><ViewportPanel /></ErrorBoundary>;
}

function SerialMonitorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Serial Monitor"><SerialMonitor /></ErrorBoundary>;
}

function PinInspectorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Pin Inspector"><PinInspector /></ErrorBoundary>;
}

function SketchEditorPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Sketch Editor"><SketchEditor /></ErrorBoundary>;
}

function SchematicPanelWrapper(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Schematic"><SchematicPanel /></ErrorBoundary>;
}

function LibraryManagerPanel(_props: IDockviewPanelProps) {
  return <ErrorBoundary name="Libraries"><LibraryManager /></ErrorBoundary>;
}

const components = {
  projectFiles: ProjectFilesPanel,
  breadboard: BreadboardDockPanel,
  inspector: InspectorPanel,
  graph: GraphEditorPanel,
  viewport: ViewportPanelWrapper,
  serialMonitor: SerialMonitorPanel,
  pinInspector: PinInspectorPanel,
  sketchEditor: SketchEditorPanel,
  schematic: SchematicPanelWrapper,
  libraryManager: LibraryManagerPanel,
};

function AppInner() {
  const { state, send } = useScene();
  const { state: boardState, send: boardSend } = useBoard();
  const { state: graphState } = useGraph();
  const project = useProject();
  useGraphPersistence();
  const { saveNow } = useBoardPersistence();
  const dockviewApiRef = useRef<DockviewApi | null>(null);
  const boardHydratedRef = useRef(false);
  const [cmdPaletteOpen, setCmdPaletteOpen] = useState(false);

  // Hydrate board state from project file on first render
  useEffect(() => {
    if (boardHydratedRef.current) return;
    boardHydratedRef.current = true;
    const pf = project.projectFile;
    if (pf.boardState) {
      boardSend({ type: "LOAD_BOARD", state: pf.boardState });
    } else {
    }
  }, [project.projectFile, boardSend]);

  // Sync codegen to board whenever graph nodes/edges change.
  // Skip during the initial hydration — graph persistence replays saved nodes,
  // which would trigger codegen and overwrite the loaded sketchCode.
  const prevNodesRef = useRef(graphState.nodes);
  const prevEdgesRef = useRef(graphState.edges);
  const graphHydratedRef = useRef(false);
  useEffect(() => {
    if (
      graphState.nodes !== prevNodesRef.current ||
      graphState.edges !== prevEdgesRef.current
    ) {
      prevNodesRef.current = graphState.nodes;
      prevEdgesRef.current = graphState.edges;
      // Skip the first change (hydration replay from useGraphPersistence)
      if (!graphHydratedRef.current) {
        graphHydratedRef.current = true;
        return;
      }
      syncCodegenToBoard(graphState.nodes, graphState.edges, boardSend);
    }
  }, [graphState.nodes, graphState.edges, boardSend]);

  // Auto-generate sketch from board components when sketch is empty/auto-generated
  const prevComponentsRef = useRef(boardState.components);
  const prevWiresRef = useRef(boardState.wires);
  useEffect(() => {
    if (
      boardState.components !== prevComponentsRef.current ||
      boardState.wires !== prevWiresRef.current
    ) {
      prevComponentsRef.current = boardState.components;
      prevWiresRef.current = boardState.wires;
      if (isAutoGeneratedSketch(boardState.sketchCode)) {
        const generated = generateSketchFromBoard(
          boardState.components,
        );
        if (generated !== boardState.sketchCode) {
          boardSend({ type: "UPDATE_SKETCH", code: generated });
        }
      }
    }
  }, [boardState.components, boardState.wires, boardState.sketchCode, boardSend]);

  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      // Cmd/Ctrl+S — save project (works from anywhere, including editors)
      if ((e.metaKey || e.ctrlKey) && e.key === "s") {
        e.preventDefault();
        saveNow();
        return;
      }

      // Cmd/Ctrl+K — command palette
      if ((e.metaKey || e.ctrlKey) && e.key === "k") {
        e.preventDefault();
        setCmdPaletteOpen((prev) => !prev);
        return;
      }

      const target = e.target as HTMLElement
      const tag = target.tagName
      if (tag === "INPUT" || tag === "TEXTAREA") return;

      // Skip when focus is inside a CodeMirror editor — it has its own undo/redo
      if (target.closest(".cm-editor")) return;

      // Undo / Redo (both scene + board)
      if ((e.metaKey || e.ctrlKey) && e.key === "z") {
        e.preventDefault();
        send({ type: e.shiftKey ? "REDO" : "UNDO" });
        boardSend({ type: e.shiftKey ? "REDO" : "UNDO" });
        return;
      }

      if (e.key === "Delete" || e.key === "Backspace") {
        if (boardState.selectedId) {
          const isWire = boardState.selectedId in (boardState.wires ?? {});
          const name = isWire
            ? "Wire"
            : boardState.components[boardState.selectedId]?.name ?? "Component";
          if (isWire) {
            boardSend({ type: "REMOVE_WIRE", id: boardState.selectedId });
          } else {
            boardSend({ type: "REMOVE_COMPONENT", id: boardState.selectedId });
          }
          boardSend({ type: "SELECT", id: null });
          toast.info(`Deleted ${name} — press Cmd+Z to undo`);
        } else if (state.selectedId) {
          send({ type: "REMOVE", id: state.selectedId });
          toast.info("Deleted — press Cmd+Z to undo");
        }
      }
      if (e.key === "Escape") {
        send({ type: "SELECT", id: null });
        boardSend({ type: "SELECT", id: null });
      }
    }
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [state.selectedId, boardState.selectedId, send, boardSend, saveNow]);

  const LAYOUT_STORAGE_KEY = "dreamer:dockview-layout";

  const onReady = useCallback((event: DockviewReadyEvent) => {
    const api = event.api;
    dockviewApiRef.current = api;

    // Clear stale layouts from before Arduino simulator conversion.
    // The old layout references "canvas" and missing panels — force a fresh default.
    const LAYOUT_VERSION = "arduino-sim-v8";
    const saved = localStorage.getItem(LAYOUT_STORAGE_KEY);
    const savedVersion = localStorage.getItem(LAYOUT_STORAGE_KEY + ":version");
    if (saved && savedVersion === LAYOUT_VERSION) {
      try {
        const layout = JSON.parse(saved) as ReturnType<DockviewApi["toJSON"]>;
        api.fromJSON(layout);
        return setupPersistence(api);
      } catch {
        localStorage.removeItem(LAYOUT_STORAGE_KEY);
      }
    } else {
      // Remove stale layout
      localStorage.removeItem(LAYOUT_STORAGE_KEY);
    }

    // Default layout: 20% / 60% / 20%
    const totalWidth = api.width;

    const projectFilesPanel = api.addPanel({
      id: "projectFiles",
      component: "projectFiles",
      title: "Project",
    });

    const canvasPanel = api.addPanel({
      id: "breadboard",
      component: "breadboard",
      title: "Breadboard",
      position: { referencePanel: projectFilesPanel, direction: "right" },
    });

    // Sketch editor is the default visible tab in the middle-right panel
    const sketchPanel = api.addPanel({
      id: "sketchEditor",
      component: "sketchEditor",
      title: "Sketch",
      position: { referencePanel: canvasPanel, direction: "right" },
    });

    api.addPanel({
      id: "graph",
      component: "graph",
      title: "Graph",
      position: { referencePanel: sketchPanel, direction: "within" },
    });

    api.addPanel({
      id: "schematic",
      component: "schematic",
      title: "Schematic",
      position: { referencePanel: sketchPanel, direction: "within" },
    });

    api.addPanel({
      id: "libraryManager",
      component: "libraryManager",
      title: "Libraries",
      position: { referencePanel: sketchPanel, direction: "within" },
    });

    // Ensure Sketch is the active tab
    sketchPanel.api.setActive();

    // Inspector is the default visible tab in the right panel
    const inspectorPanel = api.addPanel({
      id: "inspector",
      component: "inspector",
      title: "Inspector",
      position: { referencePanel: sketchPanel, direction: "right" },
    });

    api.addPanel({
      id: "pinInspector",
      component: "pinInspector",
      title: "Pin Inspector",
      position: { referencePanel: inspectorPanel, direction: "within" },
    });

    // Serial Monitor below breadboard
    api.addPanel({
      id: "serialMonitor",
      component: "serialMonitor",
      title: "Serial Monitor",
      position: { referencePanel: canvasPanel, direction: "below" },
    });

    projectFilesPanel.api.setSize({ width: totalWidth * 0.15 });
    canvasPanel.api.setSize({ width: totalWidth * 0.35 });
    sketchPanel.api.setSize({ width: totalWidth * 0.35 });
    api.getPanel("inspector")?.api.setSize({ width: totalWidth * 0.15 });

    setupPersistence(api);
  }, []);

  const debounceRef = useRef<ReturnType<typeof setTimeout>>(undefined);

  function setupPersistence(api: DockviewApi) {
    api.onDidLayoutChange(() => {
      clearTimeout(debounceRef.current);
      debounceRef.current = setTimeout(() => {
        const layout = api.toJSON();
        localStorage.setItem(LAYOUT_STORAGE_KEY, JSON.stringify(layout));
        localStorage.setItem(LAYOUT_STORAGE_KEY + ":version", "arduino-sim-v8");
      }, 300);
    });
  }

  return (
    <DockviewContext.Provider value={dockviewApiRef}>
      <div className="flex flex-col w-full h-full">
        <div className="relative flex-1 min-h-0 dockview-theme-abyss">
          <DockviewReact
            onReady={onReady}
            components={components}
            className="h-full"
          />
          <BottomToolbar />
        </div>
      </div>
      <CommandPalette open={cmdPaletteOpen} onClose={() => setCmdPaletteOpen(false)} />
    </DockviewContext.Provider>
  );
}

function AppOrDocs() {
  const { path } = useRouter();
  if (path.startsWith("/documentation")) {
    return <DocsRouter />;
  }
  return (
    <ProjectLoader>
      <BoardContext.Provider>
        <SceneContext.Provider>
          <GraphContext.Provider>
            <AppInner />
          </GraphContext.Provider>
        </SceneContext.Provider>
      </BoardContext.Provider>
    </ProjectLoader>
  );
}

export default function App() {
  return (
    <ErrorBoundary name="App">
      <Router>
        <AppOrDocs />
      </Router>
      <ToastContainer />
    </ErrorBoundary>
  );
}
