export {
  nonEmptyStringSchema,
  timestampSchema,
  vec2Schema,
  sceneSettingsSchema,
  projectSchema,
  type Project,
  sceneSchema,
  type Scene,
  entitySchema,
  type Entity,
  transformComponentSchema,
  type TransformComponent,
  spriteComponentSchema,
  type SpriteComponent,
  tilemapComponentSchema,
  type TilemapComponent,
  physicsBodyKindSchema,
  physicsBodyComponentSchema,
  type PhysicsBodyComponent,
  scriptComponentSchema,
  type ScriptComponent,
  cameraComponentSchema,
  type CameraComponent,
  componentsSchema,
  type Components,
  assetTypeSchema,
  assetSchema,
  type Asset,
  projectGraphSchema,
  type ProjectGraph,
  projectFileSchema,
  type ProjectFile,
} from "./project";

export {
  opBaseSchema,
  sceneOpSchema,
  type SceneOp,
  applyOpsRequestSchema,
  type ApplyOpsRequest,
} from "./ops";

export {
  portDataTypeSchema,
  type PortDataType,
  portDirectionSchema,
  type PortDirection,
  portSchema,
  type Port,
  graphNodeTypeSchema,
  type GraphNodeType,
  graphNodeSchema,
  type GraphNode,
  edgeSchema,
  type Edge,
  graphStateSchema,
  type GraphState,
  arePortsCompatible,
  getDefaultPorts,
} from "./graph";

export {
  graphOpSchema,
  type GraphOp,
} from "./graph-ops";

export {
  bodyKeypointNameSchema,
  type BodyKeypointName,
  animationCurveSchema,
  type AnimationCurve,
  springCurveSchema,
  type SpringCurve,
  bodyKeypointSchema,
  type BodyKeypoint,
  keyframePoseSchema,
  type KeyframePose,
  frameBoxSchema,
  type FrameBox,
  frameTransformSchema,
  type FrameTransform,
  frameTransformEditSchema,
  type FrameTransformEdit,
  motionSegmentStatusSchema,
  comfyPipelineStepStatusSchema,
  type ComfyPipelineStepStatus,
  comfyPipelineStepSchema,
  type ComfyPipelineStep,
  comfyPipelineSchema,
  type ComfyPipeline,
  motionSegmentSchema,
  type MotionSegment,
  motionProjectSchema,
  type MotionProject,
  generationProviderSchema,
  type GenerationProvider,
  generationJobStatusSchema,
  generationJobSchema,
  type GenerationJob,
} from "./motion";

// ── Arduino schemas ────────────────────────────────────────────────────────

export {
  boardTargetSchema,
  type BoardTarget,
  type BoardTargetInfo,
  type RunnerKind,
  BOARD_TARGETS,
  DEFAULT_BOARD_TARGET,
} from "./board-targets";

export {
  getBoardAnalogPins,
  getArduinoPinFromAnalogIndex,
  parseArduinoPinToken,
  isArduinoSignalPin,
  formatArduinoPin,
} from "./board-pins";

export {
  boardComponentTypeSchema,
  type BoardComponentType,
  mcuBoardTypeSchema,
  type McuBoardType,
  surfaceBoardTypeSchema,
  type SurfaceBoardType,
  componentTypeSchema,
  type ComponentType,
  BOARD_COMPONENT_TYPES,
  MCU_BOARD_TYPES,
  SURFACE_BOARD_TYPES,
  isBoardComponentType,
  isMcuBoardType,
  isSurfaceBoardType,
  pinModeSchema,
  type PinMode,
  interruptModeSchema,
  type InterruptMode,
  pinStateSchema,
  type PinState,
  servoStateSchema,
  type ServoState,
  lcdStateSchema,
  type LcdState,
  oledStateSchema,
  type OledState,
  neoPixelStateSchema,
  type NeoPixelState,
  libraryStateSchema,
  type LibraryState,
  persistedLibraryStateSchema,
  type PersistedLibraryState,
  boardComponentSchema,
  type BoardComponent,
  wireSchema,
  type Wire,
  boardStateSchema,
  type BoardState,
  customLibrarySchema,
  type CustomLibrary,
  obstacleSchema,
  type Obstacle,
  environmentSchema,
  type Environment,
  MAX_ARDUINO_PIN,
  DEFAULT_SKETCH_CODE,
  createDefaultPinStates,
  createDefaultBoardState,
} from "./arduino";

export {
  arduinoNodeTypeSchema,
  type ArduinoNodeType,
  arduinoPortDataTypeSchema,
  type ArduinoPortDataType,
} from "./arduino-graph";

export {
  boardOpBaseSchema,
  boardOpSchema,
  type BoardOp,
  applyBoardOpsRequestSchema,
  type ApplyBoardOpsRequest,
} from "./board-ops";

export {
  voltageRangeSchema,
  type VoltageRange,
  boardElectricalProfileSchema,
  type BoardElectricalProfile,
  componentElectricalProfileSchema,
  type ComponentElectricalProfile,
  pinLoadSchema,
  type PinLoad,
  railLoadSchema,
  type RailLoad,
  powerIssueSeveritySchema,
  type PowerIssueSeverity,
  powerIssueSchema,
  type PowerIssue,
  powerRecommendationSchema,
  type PowerRecommendation,
  powerBudgetReportSchema,
  type PowerBudgetReport,
} from "./electrical";

export {
  type PinPoint,
  type ComponentPinMap,
  getComponentPinNames,
  resolveComponentPins,
  resolveComponentPin,
} from "./component-pins";

// ── Diagram DSL (interchange format) ───────────────────────────────────────

export {
  DIAGRAM_SCHEMA_V1,
  diagramSchema,
  diagramToolInputSchema,
  withDiagramSchemaVersion,
  diagramComponentSchema,
  diagramWireSchema,
  diagramObstacleSchema,
  diagramEnvironmentSchema,
  diagramCustomLibrarySchema,
  type DreamerDiagram,
  type DreamerDiagramInput,
  type DiagramToolInput,
  type DiagramComponent,
  type DiagramWire,
  type DiagramObstacle,
  type DiagramEnvironment,
  type DiagramCustomLibrary,
} from "./design";

export {
  diagramToBoardState,
  boardStateToDiagram,
  type DiagramParseResult,
  type DiagramError,
} from "./diagram-adapter";

export {
  validateDiagram,
  type DiagramValidation,
  type DiagramIssue,
  type DiagramIssueSeverity,
  type DiagramIssueCategory,
  type DiagramIssueCode,
} from "./diagram-validator";

export {
  encodeDiagramForUrl,
  decodeDiagramFromUrl,
  type DecodeResult,
} from "./diagram-url";

export {
  buildExternalEditPrompt,
} from "./diagram-prompt";

// ── Circuit Program IR ─────────────────────────────────────────────────────

export {
  circuitModuleTypeSchema,
  type CircuitModuleType,
  circuitProgramModeSchema,
  type CircuitProgramMode,
  pinIntentRoleSchema,
  type PinIntentRole,
  pinIntentSchema,
  type PinIntent,
  circuitModuleSchema,
  type CircuitModule,
  netMemberSchema,
  type NetMember,
  netConstraintSchema,
  type NetConstraint,
  netSpecSchema,
  type NetSpec,
  layoutIntentSchema,
  type LayoutIntent,
  sketchIntentSchema,
  type SketchIntent,
  labelSpecSchema,
  type LabelSpec,
  componentProfileRefSchema,
  type ComponentProfileRef,
  exampleProfileRefSchema,
  type ExampleProfileRef,
  behaviorContractSchema,
  type BehaviorContract,
  circuitProgramSchema,
  type CircuitProgram,
  circuitProgramTemplateSchema,
  type CircuitProgramTemplate,
  type CircuitProgramIssue,
  type CircuitProgramValidation,
  type CircuitProgramCompileResult,
  generateCircuitProgram,
  validateCircuitProgram,
  compileCircuitProgram,
} from "./circuit-program";

export {
  BREADBOARD_FULL_ROWS,
  BREADBOARD_TERMINAL_HALF_WIDTH,
  PERFBOARD_GENERIC_COLS,
  PERFBOARD_GENERIC_ROWS,
  type RailSide,
  type RailPolarity,
  type RailHalf,
  breadboardTerminalStripId,
  breadboardRailStripId,
  breadboardTerminalStripIds,
  breadboardRailStripIds,
  breadboardFullStripIds,
  perfboardStripId,
  perfboardGenericStripIds,
  legacyRowColToStripId,
} from "./strip-ids";
