// ── Supabase generated types ────────────────────────────────────────────
//
// This file is regenerated by `bun run db:types` (which calls
// `bunx supabase gen types typescript --local`). Do not edit by hand.
//
// PR1 only uses the untyped `SupabaseClient` for auth verification, so
// this placeholder is fine until PR2 wires the typed DB repos.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string
          owner_id: string
          name: string
          version: number
          data: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          owner_id: string
          name: string
          version?: number
          data: Json
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database["public"]["Tables"]["projects"]["Insert"]>
        Relationships: []
      }
      threads: {
        Row: {
          id: string
          project_id: string
          data: Json
          updated_at: string
        }
        Insert: {
          id: string
          project_id: string
          data: Json
          updated_at?: string
        }
        Update: Partial<Database["public"]["Tables"]["threads"]["Insert"]>
        Relationships: []
      }
      agent_runs: {
        Row: {
          id: string
          thread_id: string
          project_id: string
          status: string
          data: Json
          created_at: string
        }
        Insert: {
          id: string
          thread_id: string
          project_id: string
          status: string
          data: Json
          created_at?: string
        }
        Update: Partial<Database["public"]["Tables"]["agent_runs"]["Insert"]>
        Relationships: []
      }
      audit_events: {
        Row: {
          id: number
          ts: string
          user_id: string | null
          action: string
          project_id: string | null
          extra: Json | null
        }
        Insert: {
          id?: number
          ts?: string
          user_id?: string | null
          action: string
          project_id?: string | null
          extra?: Json | null
        }
        Update: Partial<Database["public"]["Tables"]["audit_events"]["Insert"]>
        Relationships: []
      }
      app_logs: {
        Row: {
          id: number
          ts: string
          level: string
          tag: string
          message: string
          data: Json | null
          user_id: string | null
          request_id: string | null
        }
        Insert: {
          id?: number
          ts?: string
          level: string
          tag: string
          message: string
          data?: Json | null
          user_id?: string | null
          request_id?: string | null
        }
        Update: Partial<Database["public"]["Tables"]["app_logs"]["Insert"]>
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
