import type { ComponentElectricalProfile, ComponentType } from "@dreamer/schemas";

const DEFAULT_PROFILE: ComponentElectricalProfile = {
  type: "unknown",
  signalPinCurrentMa: 0,
  typicalCurrentMa: 0,
  peakCurrentMa: 0,
  startupCurrentMa: 0,
  mustUseExternalPower: false,
  notes: "No electrical profile available.",
};

export const COMPONENT_ELECTRICAL_PROFILES: Partial<Record<ComponentType, ComponentElectricalProfile>> = {
  led: {
    type: "led",
    nominalVoltage: 2.0,
    voltageRange: { min: 1.8, max: 3.3 },
    signalPinCurrentMa: 10,
    typicalCurrentMa: 10,
    peakCurrentMa: 20,
    startupCurrentMa: 0,
    mustUseExternalPower: false,
    notes: "Typical indicator LED with resistor.",
  },
  rgb_led: {
    type: "rgb_led",
    nominalVoltage: 2.0,
    voltageRange: { min: 1.8, max: 3.3 },
    signalPinCurrentMa: 20,
    typicalCurrentMa: 30,
    peakCurrentMa: 60,
    startupCurrentMa: 0,
    mustUseExternalPower: false,
    notes: "Assumes at most one to two channels active with resistor(s).",
  },
  buzzer: {
    type: "buzzer",
    nominalVoltage: 5,
    voltageRange: { min: 3, max: 5 },
    signalPinCurrentMa: 20,
    typicalCurrentMa: 25,
    peakCurrentMa: 35,
    startupCurrentMa: 40,
    mustUseExternalPower: false,
  },
  servo: {
    type: "servo",
    nominalVoltage: 5,
    voltageRange: { min: 4.8, max: 6 },
    signalPinCurrentMa: 2,
    typicalCurrentMa: 180,
    peakCurrentMa: 500,
    startupCurrentMa: 650,
    mustUseExternalPower: true,
    notes: "Signal pin is low current; motor rail should be external.",
  },
  dc_motor: {
    type: "dc_motor",
    nominalVoltage: 5,
    voltageRange: { min: 3, max: 9 },
    signalPinCurrentMa: 2,
    typicalCurrentMa: 250,
    peakCurrentMa: 1200,
    startupCurrentMa: 1200,
    mustUseExternalPower: true,
  },
  relay: {
    type: "relay",
    nominalVoltage: 5,
    voltageRange: { min: 4.5, max: 5.5 },
    signalPinCurrentMa: 2,
    typicalCurrentMa: 70,
    peakCurrentMa: 90,
    startupCurrentMa: 90,
    mustUseExternalPower: true,
    notes: "Typically requires a transistor/driver stage.",
  },
  neopixel: {
    type: "neopixel",
    nominalVoltage: 5,
    voltageRange: { min: 4.5, max: 5.5 },
    signalPinCurrentMa: 2,
    typicalCurrentMa: 30,
    peakCurrentMa: 60,
    startupCurrentMa: 60,
    mustUseExternalPower: true,
  },
  lcd_16x2: {
    type: "lcd_16x2",
    nominalVoltage: 5,
    signalPinCurrentMa: 2,
    typicalCurrentMa: 20,
    peakCurrentMa: 30,
    startupCurrentMa: 30,
    mustUseExternalPower: false,
  },
  seven_segment: {
    type: "seven_segment",
    nominalVoltage: 2,
    signalPinCurrentMa: 10,
    typicalCurrentMa: 40,
    peakCurrentMa: 80,
    startupCurrentMa: 0,
    mustUseExternalPower: false,
    notes: "Typical single-digit display can be powered from Arduino rails when segment current is resistor-limited.",
  },
  photoresistor: {
    type: "photoresistor",
    nominalVoltage: 5,
    signalPinCurrentMa: 1,
    typicalCurrentMa: 1,
    peakCurrentMa: 2,
    startupCurrentMa: 0,
    mustUseExternalPower: false,
  },
  temperature_sensor: {
    type: "temperature_sensor",
    nominalVoltage: 5,
    signalPinCurrentMa: 1,
    typicalCurrentMa: 1,
    peakCurrentMa: 2,
    startupCurrentMa: 0,
    mustUseExternalPower: false,
  },
  ultrasonic_sensor: {
    type: "ultrasonic_sensor",
    nominalVoltage: 5,
    signalPinCurrentMa: 2,
    typicalCurrentMa: 15,
    peakCurrentMa: 20,
    startupCurrentMa: 20,
    mustUseExternalPower: false,
  },
  pir_sensor: {
    type: "pir_sensor",
    nominalVoltage: 5,
    signalPinCurrentMa: 1,
    typicalCurrentMa: 8,
    peakCurrentMa: 15,
    startupCurrentMa: 20,
    mustUseExternalPower: false,
  },
  dht_sensor: {
    type: "dht_sensor",
    nominalVoltage: 5,
    signalPinCurrentMa: 1,
    typicalCurrentMa: 2,
    peakCurrentMa: 3,
    startupCurrentMa: 3,
    mustUseExternalPower: false,
  },
  ir_receiver: {
    type: "ir_receiver",
    nominalVoltage: 5,
    signalPinCurrentMa: 1,
    typicalCurrentMa: 1,
    peakCurrentMa: 2,
    startupCurrentMa: 0,
    mustUseExternalPower: false,
  },
  oled_display: {
    type: "oled_display",
    nominalVoltage: 5,
    signalPinCurrentMa: 2,
    typicalCurrentMa: 20,
    peakCurrentMa: 30,
    startupCurrentMa: 30,
    mustUseExternalPower: false,
  },
  power_supply: {
    type: "power_supply",
    nominalVoltage: 5,
    signalPinCurrentMa: 0,
    typicalCurrentMa: 0,
    peakCurrentMa: 0,
    startupCurrentMa: 0,
    mustUseExternalPower: false,
    notes: "Represents external supply source in planning.",
  },
};

export function getComponentElectricalProfile(type: ComponentType): ComponentElectricalProfile {
  return COMPONENT_ELECTRICAL_PROFILES[type] ?? { ...DEFAULT_PROFILE, type };
}
