// AUTO-GENERATED by scripts/generate-asset-manifest.ts — do not edit.
// Regenerated before each `bun build --compile`.
// @ts-nocheck -- Bun's file-import attribute returns a string path at
// runtime, but TS typings infer bundle types from extensions. Runtime
// behavior is correct; silencing the type-check noise here.

import asset__assets_arduino_uno_board_DBpS0kIP_svg from "../../app/dist/assets/arduino-uno-board-DBpS0kIP.svg" with { type: "file" }
import asset__assets_index_CCUjAQjo_js from "../../app/dist/assets/index-CCUjAQjo.js" with { type: "file" }
import asset__assets_index_ClMqH84B_js from "../../app/dist/assets/index-ClMqH84B.js" with { type: "file" }
import asset__assets_index_DzrLtLgd_css from "../../app/dist/assets/index-DzrLtLgd.css" with { type: "file" }
import asset__index_html from "../../app/dist/index.html" with { type: "file" }

export const EMBEDDED_ASSETS: Record<string, string> = {
  "/assets/arduino-uno-board-DBpS0kIP.svg": asset__assets_arduino_uno_board_DBpS0kIP_svg as unknown as string,
  "/assets/index-CCUjAQjo.js": asset__assets_index_CCUjAQjo_js as unknown as string,
  "/assets/index-ClMqH84B.js": asset__assets_index_ClMqH84B_js as unknown as string,
  "/assets/index-DzrLtLgd.css": asset__assets_index_DzrLtLgd_css as unknown as string,
  "/index.html": asset__index_html as unknown as string,
  "/": asset__index_html as unknown as string,
}

export const ASSET_COUNT = 5
