#!/usr/bin/env bun
// ── Vendor the RP2040 bootrom ─────────────────────────────────────────────
//
// Populates packages/app/src/simulator/rp2040-bootrom-data.ts with a base64
// copy of the 16 KB RP2040 first-stage bootrom so the in-browser Pico
// simulator can boot real firmware (clocks/PLL/USB-CDC) instead of the
// synthesised GPIO-only handoff. See rp2040-bootrom.ts for the why.
//
// The bootrom is © Raspberry Pi, BSD-3-Clause, and freely redistributable.
// We vendor it locally (verified) rather than committing a binary blind.
//
// Usage:
//   bun run bootrom:fetch --file /path/to/bootrom.bin     # trusted local copy
//   bun run bootrom:fetch --url  https://…/bootrom.bin    # download
//   bun run bootrom:fetch                                  # default URL below
//   bun run bootrom:fetch --expect-sha256 <hex>            # fail unless it matches
//
// A trustworthy local source is the Pico SDK / OpenOCD / picotool install,
// which ship the bootrom binary. Whatever source you use, the script prints
// the SHA-256 so you can cross-check it against Raspberry Pi's published hash.

import { createHash } from "node:crypto"
import { resolve } from "node:path"

// rp2040js's demo bootrom (B-stepping). Documented default; verify the printed
// SHA-256 against an authoritative source before trusting it in production.
const DEFAULT_URL =
  "https://raw.githubusercontent.com/wokwi/rp2040js/main/demo/bootrom.bin"

const BOOTROM_BYTES = 16 * 1024
const OUT_PATH = resolve(
  import.meta.dir,
  "../packages/app/src/simulator/rp2040-bootrom-data.ts",
)

function parseArgs(argv: string[]): {
  file?: string
  url?: string
  expectSha256?: string
} {
  const out: { file?: string; url?: string; expectSha256?: string } = {}
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === "--file") out.file = argv[++i]
    else if (a === "--url") out.url = argv[++i]
    else if (a === "--expect-sha256") out.expectSha256 = argv[++i]?.toLowerCase()
  }
  return out
}

async function readSource(args: {
  file?: string
  url?: string
}): Promise<{ bytes: Uint8Array; origin: string }> {
  if (args.file) {
    const f = Bun.file(args.file)
    if (!(await f.exists())) throw new Error(`--file not found: ${args.file}`)
    return { bytes: new Uint8Array(await f.arrayBuffer()), origin: args.file }
  }
  const url = args.url ?? DEFAULT_URL
  const res = await fetch(url)
  if (!res.ok) {
    throw new Error(`download failed: ${res.status} ${res.statusText} (${url})`)
  }
  return { bytes: new Uint8Array(await res.arrayBuffer()), origin: url }
}

function generatedFile(base64: string, sha256: string, origin: string): string {
  return `// ── RP2040 bootrom data (generated / vendored) ───────────────────────────
//
// AUTO-GENERATED by \`bun run bootrom:fetch\` (scripts/fetch-rp2040-bootrom.ts).
// Do NOT edit by hand — re-run the script to regenerate.
//
// Source:  ${origin}
// SHA-256: ${sha256}
// © Raspberry Pi, BSD-3-Clause. 16 KB RP2040 first-stage bootrom.
//
// See rp2040-bootrom.ts for how this is decoded and why it's vendored, not
// committed blind.

/** base64 of the 16 KB bootrom, or null when not vendored. */
export const RP2040_BOOTROM_BASE64: string | null =
  "${base64}"

/** Lowercase hex SHA-256 of the decoded bootrom, for provenance/verification. */
export const RP2040_BOOTROM_SHA256: string | null = "${sha256}"
`
}

async function main(): Promise<void> {
  const args = parseArgs(Bun.argv.slice(2))
  const { bytes, origin } = await readSource(args)

  if (bytes.byteLength !== BOOTROM_BYTES) {
    throw new Error(
      `expected a ${BOOTROM_BYTES}-byte bootrom, got ${bytes.byteLength} bytes from ${origin}. ` +
        `This doesn't look like an RP2040 bootrom — re-check --file/--url.`,
    )
  }

  const sha256 = createHash("sha256").update(bytes).digest("hex")
  if (args.expectSha256 && args.expectSha256 !== sha256) {
    throw new Error(
      `SHA-256 mismatch: got ${sha256}, expected ${args.expectSha256}. Refusing to write.`,
    )
  }

  const base64 = Buffer.from(bytes).toString("base64")
  await Bun.write(OUT_PATH, generatedFile(base64, sha256, origin))

  console.log(`✓ wrote ${OUT_PATH}`)
  console.log(`  source:  ${origin}`)
  console.log(`  size:    ${bytes.byteLength} bytes`)
  console.log(`  sha256:  ${sha256}`)
  console.log(`\nCross-check that SHA-256 against an authoritative source before trusting it.`)
}

main().catch((err) => {
  console.error(`✗ ${err instanceof Error ? err.message : String(err)}`)
  process.exit(1)
})
