#!/usr/bin/env bun
// ── Asset manifest generator ─────────────────────────────────────────────
//
// Scans `packages/app/dist/` after a Vite build and writes
// `packages/cli/src/web-ui-manifest.generated.ts` — a TypeScript module
// that statically imports every built asset with `with { type: "file" }`.
// Those imports cause `bun build --compile` to embed the files inside
// the produced binary, and give us absolute paths we can read at runtime
// via `Bun.file()`.
//
// Run this every time before `bun build --compile`. The manifest is
// gitignored — its contents depend on the Vite hash of the current build.

import { readdirSync, statSync, writeFileSync, existsSync } from "fs"
import { join, relative, posix } from "path"

const REPO_ROOT = join(import.meta.dir, "..")
const DIST_DIR = join(REPO_ROOT, "packages", "app", "dist")
const OUTPUT_FILE = join(REPO_ROOT, "packages", "cli", "src", "web-ui-manifest.generated.ts")

function walk(dir: string, acc: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    const stat = statSync(full)
    if (stat.isDirectory()) walk(full, acc)
    else acc.push(full)
  }
  return acc
}

function safeIdentifier(path: string): string {
  // Convert path segments into a valid TS identifier: a/b-c.js → a_b_c_js
  return "asset_" + path.replace(/[^a-zA-Z0-9]/g, "_")
}

function writeEmptyManifest(reason: string): void {
  const lines = [
    "// AUTO-GENERATED by scripts/generate-asset-manifest.ts — do not edit.",
    `// Empty manifest: ${reason}`,
    "// The CLI falls back to dev-mode Vite spawn when ASSET_COUNT is 0.",
    "",
    "export const EMBEDDED_ASSETS: Record<string, string> = {}",
    "export const ASSET_COUNT = 0",
    "",
  ]
  writeFileSync(OUTPUT_FILE, lines.join("\n"))
}

function main() {
  if (!existsSync(DIST_DIR)) {
    writeEmptyManifest(`${DIST_DIR} does not exist; run \`bun run build:webui\` before compiling a standalone binary.`)
    console.log(`⚠ No dist/ found — wrote empty manifest. Run \`bun run build:webui\` before \`bun build --compile\`.`)
    return
  }

  const files = walk(DIST_DIR).sort()
  if (files.length === 0) {
    writeEmptyManifest(`${DIST_DIR} is empty.`)
    console.log(`⚠ dist/ is empty — wrote empty manifest.`)
    return
  }

  const entries: Array<{ urlPath: string; importPath: string; ident: string }> = []
  for (const absFile of files) {
    // URL path the browser will request — always forward slashes.
    const rel = relative(DIST_DIR, absFile)
    const urlPath = "/" + rel.split(/[\\/]/).join("/")

    // Import path relative to OUTPUT_FILE (posix form since TS paths use /).
    const importPath = posix.relative(
      posix.dirname(OUTPUT_FILE.split(/[\\/]/).join("/")),
      absFile.split(/[\\/]/).join("/"),
    )
    const importPathRel = importPath.startsWith(".") ? importPath : "./" + importPath

    entries.push({
      urlPath,
      importPath: importPathRel,
      ident: safeIdentifier(urlPath),
    })
  }

  const lines: string[] = []
  lines.push("// AUTO-GENERATED by scripts/generate-asset-manifest.ts — do not edit.")
  lines.push("// Regenerated before each `bun build --compile`.")
  lines.push("// @ts-nocheck -- Bun's file-import attribute returns a string path at")
  lines.push("// runtime, but TS typings infer bundle types from extensions. Runtime")
  lines.push("// behavior is correct; silencing the type-check noise here.")
  lines.push("")
  for (const { importPath, ident } of entries) {
    lines.push(`import ${ident} from "${importPath}" with { type: "file" }`)
  }
  lines.push("")
  lines.push("export const EMBEDDED_ASSETS: Record<string, string> = {")
  for (const { urlPath, ident } of entries) {
    lines.push(`  "${urlPath}": ${ident} as unknown as string,`)
    if (urlPath === "/index.html") {
      lines.push(`  "/": ${ident} as unknown as string,`)
    }
  }
  lines.push("}")
  lines.push("")
  lines.push(`export const ASSET_COUNT = ${entries.length}`)
  lines.push("")

  writeFileSync(OUTPUT_FILE, lines.join("\n"))
  console.log(`✓ Wrote ${entries.length} asset(s) to ${relative(REPO_ROOT, OUTPUT_FILE)}`)
}

main()
