// ── Board-to-Sketch Generator ──────────────────────────────────────────────
//
// Generates a starter Arduino sketch from the current breadboard layout.
// This is a helper that produces sensible default code — users can modify it.

import {
  DEFAULT_SKETCH_CODE,
  isBoardComponentType,
  type BoardComponent,
  type Wire,
} from "@dreamer/schemas"
import { getComponentDef } from "@/components/registry"
import { findArduinoPinsForComponent } from "@/breadboard/component-pin-resolver"

/** Marker comment used to detect auto-generated sketches */
const AUTO_GENERATED_MARKER = "// Auto-generated from board layout"

/**
 * Returns true if the given sketch code is empty or was auto-generated
 * (and therefore safe to overwrite).
 */
export function isAutoGeneratedSketch(code: string): boolean {
  const trimmed = code.trim()
  return (
    trimmed === "" ||
    trimmed === DEFAULT_SKETCH_CODE.trim() ||
    trimmed.startsWith(AUTO_GENERATED_MARKER)
  )
}

/**
 * Generate Arduino sketch code from the board's component layout.
 *
 * For each component with an assigned pin, appropriate setup/loop code
 * is generated. If no pins are assigned, a comment-only sketch is produced.
 */
export function generateSketchFromBoard(
  components: Record<string, BoardComponent>,
  wires?: Record<string, Wire>,
): string {
  const entries = Object.values(components)
  if (entries.length === 0) {
    return DEFAULT_SKETCH_CODE
  }

  const setupLines: string[] = []
  const loopLines: string[] = []
  const globalLines: string[] = []
  const includeServo = entries.some((c) => c.type === "servo")

  let hasAnyPin = false

  for (const comp of entries) {
    const def = getComponentDef(comp.type)
    if (!def?.generateSketch) continue

    // If pins aren't explicitly assigned, try resolving them from wires.
    // This lets the auto-generator produce code for wire-based boards
    // (the common case) where comp.pins are all null.
    let resolvedComp = comp
    if (wires) {
      const hasExplicit = Object.values(comp.pins).some((v) => v != null)
      if (!hasExplicit) {
        const wirePins = findArduinoPinsForComponent(comp, wires)
        if (wirePins.length > 0) {
          const pinNames = Object.keys(comp.pins)
          const newPins = { ...comp.pins }
          for (let i = 0; i < Math.min(pinNames.length, wirePins.length); i++) {
            newPins[pinNames[i]] = wirePins[i]
          }
          resolvedComp = { ...comp, pins: newPins }
        }
      }
    }

    const out = def.generateSketch(resolvedComp)
    if (!out) continue
    if (out.globalLines) globalLines.push(...out.globalLines)
    if (out.setupLines) setupLines.push(...out.setupLines)
    if (out.loopLines) loopLines.push(...out.loopLines)
    if (out.hasPin) hasAnyPin = true
  }

  if (!hasAnyPin) {
    // No pins assigned — produce a comment-only sketch
    const componentList = entries
      .filter((c) => !isBoardComponentType(c.type) && c.type !== "wire")
      .map((c) => `//   - ${c.name} (${c.type})`)
      .join("\n")

    return [
      AUTO_GENERATED_MARKER,
      "// Components placed on the breadboard:",
      componentList,
      "//",
      "// Assign pins in the Inspector panel to generate setup code.",
      "",
      "void setup() {",
      "}",
      "",
      "void loop() {",
      "}",
      "",
    ].join("\n")
  }

  // Build full sketch
  const lines: string[] = [AUTO_GENERATED_MARKER]

  if (includeServo) {
    lines.push("#include <Servo.h>")
  }

  if (globalLines.length > 0) {
    lines.push("")
    lines.push(...globalLines)
  }

  lines.push("")
  lines.push("void setup() {")
  lines.push("  Serial.begin(9600);")
  lines.push(...setupLines)
  lines.push("}")
  lines.push("")
  lines.push("void loop() {")
  if (loopLines.length > 0) {
    lines.push(...loopLines)
  }
  lines.push("  delay(100);")
  lines.push("}")
  lines.push("")

  return lines.join("\n")
}
