// ── Board-to-Sketch Generator ──────────────────────────────────────────────
//
// Generates a starter Arduino sketch from the current breadboard layout.
// This is a helper that produces sensible default code — users can modify it.

import type { BoardComponent, Wire } from "@dreamer/schemas"

/** Marker comment used to detect auto-generated sketches */
export const AUTO_GENERATED_MARKER = "// Auto-generated from board layout"

/**
 * Returns true if the given sketch code is empty or was auto-generated
 * (and therefore safe to overwrite).
 */
export function isAutoGeneratedSketch(code: string): boolean {
  const trimmed = code.trim()
  return trimmed === "" || trimmed.startsWith(AUTO_GENERATED_MARKER)
}

/**
 * Generate Arduino sketch code from the board's component layout.
 *
 * For each component with an assigned pin, appropriate setup/loop code
 * is generated. If no pins are assigned, a comment-only sketch is produced.
 */
export function generateSketchFromBoard(
  components: Record<string, BoardComponent>,
  wires: Record<string, Wire>,
): string {
  const entries = Object.values(components)
  if (entries.length === 0) {
    return ""
  }

  const setupLines: string[] = []
  const loopLines: string[] = []
  const includeServo = entries.some((c) => c.type === "servo")
  const globalLines: string[] = []

  let hasAnyPin = false
  let servoCount = 0

  for (const comp of entries) {
    const assignedPins = getAssignedPins(comp)

    switch (comp.type) {
      case "led": {
        const pin = assignedPins.anode ?? assignedPins.cathode
        if (pin != null) {
          hasAnyPin = true
          setupLines.push(`  pinMode(${pin}, OUTPUT); // ${comp.name}`)
          loopLines.push(`  digitalWrite(${pin}, HIGH); // ${comp.name}`)
        }
        break
      }
      case "rgb_led": {
        for (const [label, pin] of Object.entries(assignedPins)) {
          if (pin != null && label !== "cathode") {
            hasAnyPin = true
            setupLines.push(`  pinMode(${pin}, OUTPUT); // ${comp.name} ${label}`)
            loopLines.push(`  analogWrite(${pin}, 128); // ${comp.name} ${label}`)
          }
        }
        break
      }
      case "button": {
        const pin = assignedPins.a ?? assignedPins.b
        if (pin != null) {
          hasAnyPin = true
          setupLines.push(`  pinMode(${pin}, INPUT_PULLUP); // ${comp.name}`)
        }
        break
      }
      case "servo": {
        const pin = assignedPins.signal
        if (pin != null) {
          hasAnyPin = true
          const varName = servoCount === 0 ? "myServo" : `myServo${servoCount}`
          globalLines.push(`Servo ${varName};`)
          setupLines.push(`  ${varName}.attach(${pin}); // ${comp.name}`)
          loopLines.push(`  ${varName}.write(90); // ${comp.name}`)
          servoCount++
        }
        break
      }
      case "buzzer": {
        const pin = assignedPins.positive
        if (pin != null) {
          hasAnyPin = true
          setupLines.push(`  pinMode(${pin}, OUTPUT); // ${comp.name}`)
        }
        break
      }
      case "lcd_16x2": {
        const { rs, en, d4, d5, d6, d7 } = assignedPins
        if (rs != null && en != null && d4 != null && d5 != null && d6 != null && d7 != null) {
          hasAnyPin = true
          globalLines.push(`LiquidCrystal lcd(${rs}, ${en}, ${d4}, ${d5}, ${d6}, ${d7});`)
          setupLines.push(`  lcd.begin(16, 2); // ${comp.name}`)
          loopLines.push(`  lcd.setCursor(0, 0);`)
          loopLines.push(`  lcd.print("Hello, World!");`)
        }
        break
      }
      case "potentiometer": {
        const pin = assignedPins.signal
        if (pin != null) {
          hasAnyPin = true
          setupLines.push(`  // ${comp.name} on analog pin ${pin}`)
        }
        break
      }
      case "photoresistor": {
        const pin = assignedPins.a ?? assignedPins.b
        if (pin != null) {
          hasAnyPin = true
          setupLines.push(`  // ${comp.name} on analog pin ${pin}`)
        }
        break
      }
      case "temperature_sensor": {
        const pin = assignedPins.signal
        if (pin != null) {
          hasAnyPin = true
          setupLines.push(`  // ${comp.name} on pin ${pin}`)
        }
        break
      }
      case "ultrasonic_sensor": {
        const { trigger, echo } = assignedPins
        if (trigger != null) {
          hasAnyPin = true
          setupLines.push(`  pinMode(${trigger}, OUTPUT); // ${comp.name} trigger`)
        }
        if (echo != null) {
          hasAnyPin = true
          setupLines.push(`  pinMode(${echo}, INPUT); // ${comp.name} echo`)
        }
        break
      }
      default:
        break
    }
  }

  if (!hasAnyPin) {
    // No pins assigned — produce a comment-only sketch
    const componentList = entries
      .filter((c) => c.type !== "arduino_uno" && c.type !== "wire")
      .map((c) => `//   - ${c.name} (${c.type})`)
      .join("\n")

    return [
      AUTO_GENERATED_MARKER,
      "// Components placed on the breadboard:",
      componentList,
      "//",
      "// Assign pins in the Inspector panel to generate setup code.",
      "",
      "void setup() {",
      "}",
      "",
      "void loop() {",
      "}",
      "",
    ].join("\n")
  }

  // Build full sketch
  const lines: string[] = [AUTO_GENERATED_MARKER]

  if (includeServo) {
    lines.push("#include <Servo.h>")
  }

  if (globalLines.length > 0) {
    lines.push("")
    lines.push(...globalLines)
  }

  lines.push("")
  lines.push("void setup() {")
  lines.push("  Serial.begin(9600);")
  lines.push(...setupLines)
  lines.push("}")
  lines.push("")
  lines.push("void loop() {")
  if (loopLines.length > 0) {
    lines.push(...loopLines)
  }
  lines.push("  delay(100);")
  lines.push("}")
  lines.push("")

  return lines.join("\n")
}

/** Extract assigned (non-null) pins from a component */
function getAssignedPins(comp: BoardComponent): Record<string, number | null> {
  return comp.pins
}
