// ── RP2040 bootrom loader ────────────────────────────────────────────────
//
// rp2040js ships no bootrom. The real 16 KB first-stage ROM is what:
//   - reads the 256-byte boot2 stage from flash and checksums it,
//   - hands off to the firmware's vector table (flash + 0x100 on Arduino-Pico),
//   - exposes the ROM function table (`rom_func_lookup`, flash helpers,
//     `reset_usb_boot`, fast clz/popcount, …) that pico-sdk code calls,
//   - and lets the SDK runtime bring up XOSC / PLLs / clocks correctly.
//
// Without it the runner has to SYNTHESISE the boot handoff (read SP/PC from
// flash+0x100 directly), which only carries GPIO-only sketches — clocks,
// timing, and USB CDC misbehave. Loading the real bootrom unblocks all of it
// in one move; see runners/rp2040-runner.ts for the handoff.
//
// The bootrom is open source (Raspberry Pi, BSD-3-Clause) and redistributable,
// but we don't commit the binary blind. `rp2040-bootrom-data.ts` holds a
// base64 copy (or `null`), regenerated by `bun run bootrom:fetch`, which
// downloads/loads + SHA-256-verifies it. When the data is null this returns
// null and the runner falls back to the synthesised handoff.

const BOOTROM_WORDS = 0x4000 / 4 // 16 KB ROM as 32-bit words (matches RP2040.bootrom)

// undefined = not yet attempted; null = attempted, none vendored.
let cached: Uint32Array | null | undefined

function decodeBase64(b64: string): Uint8Array {
  if (typeof atob === "function") {
    const bin = atob(b64)
    const bytes = new Uint8Array(bin.length)
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i)
    return bytes
  }
  // Bun/Node fallback (atob exists in both, but guard for exotic runtimes).
  return Uint8Array.from(Buffer.from(b64, "base64"))
}

/**
 * Decode a base64 bootrom into a `Uint32Array` of exactly 16 KB (4096 words),
 * little-endian. Zero-pads a short blob and truncates a long one, because
 * `RP2040.loadBootrom()` does a straight `.set()` that throws on a length
 * mismatch. Exported for testing.
 */
export function decodeBootrom(b64: string): Uint32Array {
  const bytes = decodeBase64(b64)
  const words = new Uint32Array(BOOTROM_WORDS)
  const usableBytes = Math.min(bytes.byteLength, BOOTROM_WORDS * 4)
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)
  for (let i = 0; i < Math.floor(usableBytes / 4); i++) {
    words[i] = view.getUint32(i * 4, true)
  }
  return words
}

/**
 * Decode the vendored bootrom into a `Uint32Array` for `RP2040.loadBootrom()`.
 * Returns null when no bootrom is vendored so callers can fall back. The data
 * module is dynamic-imported so its base64 only loads (in its own chunk) when
 * a Pico sketch actually runs. Result is cached for the session.
 */
export async function loadRp2040Bootrom(): Promise<Uint32Array | null> {
  if (cached !== undefined) return cached
  const { RP2040_BOOTROM_BASE64 } = await import("./rp2040-bootrom-data")
  cached = RP2040_BOOTROM_BASE64 ? decodeBootrom(RP2040_BOOTROM_BASE64) : null
  return cached
}
