// ── RP2040 bootrom data (generated / vendored) ───────────────────────────
//
// AUTO-GENERATED by `bun run bootrom:fetch` (scripts/fetch-rp2040-bootrom.ts).
// Do NOT edit by hand — re-run the script to regenerate.
//
// Holds the base64-encoded 16 KB RP2040 first-stage bootrom (BSD-3-Clause,
// © Raspberry Pi). It ships as `null` by default: the binary is fetched and
// verified locally rather than committed blind, so a fresh checkout has no
// bootrom and the simulator falls back to a synthesised boot handoff (GPIO
// works; clocks/PLL/USB-CDC don't — see rp2040-bootrom.ts and
// runners/rp2040-runner.ts).
//
// To enable full Pico simulation:
//   bun run bootrom:fetch --file /path/to/bootrom.bin
//   bun run bootrom:fetch --url  https://…/bootrom.bin
//
// This file is intentionally tiny when null so it tree-shakes to nothing; the
// loader dynamic-imports it, keeping the (large) base64 out of the main bundle.

/** base64 of the 16 KB bootrom, or null when not vendored. */
export const RP2040_BOOTROM_BASE64: string | null = null

/** Lowercase hex SHA-256 of the decoded bootrom, for provenance/verification. */
export const RP2040_BOOTROM_SHA256: string | null = null
